apiVersion: v1
kind: Pod
metadata:
    name: pvpod
spec:
    containers:
        - name: test-container
          image: k8s.gcr.io/test-webserver
          volumeMounts:
            - name: test-volume
              mountPath: /test-vmdk
          securityContext:
            capabilities:
                drop:
                    - NET_RAW
                    - ALL
    volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: pvc0001
